const usersTypes = {
  CREATE_USER_REQUEST: 'users/CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'users/CREATE_USER_SUCCESS',
  GET_ALL_USERS_REQUEST: 'users/GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'users/GET_ALL_USERS_SUCCESS',
};

export default usersTypes;
