export const applicationStates = Object.freeze({
  IDLE: 'IDLE',
  BUSY: 'BUSY',
  CASE_FETCHED: 'CASE FETCHED',
  CASES_ADDED: 'CASES ADDED',
  CASE_ACTIVE: 'CASE ACTIVE',
  DELETE_POINTS: 'DELETE POINTS',
  EDIT_POINT: 'EDIT POINT',
  ADD_POINT: 'ADD POINT',
  STAGE_CASE: 'STAGE CASE',
  SUBMIT_FOR_PUBLISHING: 'SUBMIT FOR PUBLISHING',
  FORGOT_PASSWORD: 'FORGOT PASSWORD',
  REQUEST_PASSWORD_LINK: 'REQUEST PASSWORD LINK',
});
